name: Next.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.1'
   
    - name: Upgrade npm to latest version
      run: npm install -g npm@latest

    - name: Upgrade yarn to latest version
      run: npm install -g yarn@latest

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Run dev
      run: yarn dev